export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="dracula"

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
  	bgnotify
  	vscode
)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh